name: Deploy file from another repo via SSH key

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target server IP"
        required: true
      server_user:
        description: "Target server username"
        required: true

jobs:
  build-artifact:
    runs-on: [self-hosted, mohit_runner]

    steps:
      - name: Checkout Repo A (current repo)
        uses: actions/checkout@v3

      - name: Checkout Repo B (private via GitHub deploy key)
        uses: actions/checkout@v3
        with:
          repository: MohitthakurOP/devops1
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}   # Deploy key for Repo B
          ref: main
          path: repo-b
          persist-credentials: false
          ssh-strict: false

      - name: Archive artifact
        run: |
          mkdir -p artifact
          cp repo-b/index.php artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifact
          path: artifact/

  deploy:
    runs-on: self-hosted
    needs: build-artifact

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifact
          path: artifact

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ github.event.inputs.server_user }}@${{ github.event.inputs.server_ip }} "echo Connected OK"

      - name: Copy artifact to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ github.event.inputs.server_ip }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "artifact/index.php"
          target: "/data"
          overwrite: true
          debug: true
