name: Simple SSH Workflow

on:
  push:
    branches:
      - main
jobs:
  ssh-job:
    runs-on: [self-hosted, mohit_runner]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Connect to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 30s
          script: |
            echo "Connected successfully!"
            hostname
            pwd
            ls -l
